### ISSUE TITLE
[Safari] IndexedDB database in browser closing unexpectedly after being idle

### ISSUE THREAD

**Issue by leoric23** [anaestheticsapp/logbook#14] opened 2020-07-13 16:42 UTC
after being idle to the point of being automatically logged out of the current session i cannot re-login on my iphone unless i force the app closed and restart it. error message as seen in the attached screenshot

![canvas](https://user-images.githubusercontent.com/6105668/87332012-33249800-c53b-11ea-8c79-10ab1bc739a1.png)

**Comment by anaestheticsapp** [comment] 2020-07-13 20:20
Interesting - was this a one off or can you consistently reproduce this? Please let me know if you see this again.

Unfortunately, Safari has become very buggy with iOS 13. Seems to be a problem when closing the app whilst the database connection is open. Previously had this issue with the Page Lifecycle API which frequently opens and closes the database based on page visibility. Deactivating this for Safari gave me a bit more stability.

Related bugs:
https://bugs.webkit.org/show_bug.cgi?id=197050

Code should be updated with the next update to help debug this
* Add navigator beacon to send error reports
* Add error reporting to onclose event (triggers when database is unexpectedly closed)
* May have to introduce new error method to reset IDB connection (requires rewrite of all IDB calls)

**Comment by leoric23** [comment] 2020-07-14 16:53
i am using iOS 13.3

it has happened a couple of times, but not again since i posted. i will try to figure out more detailed circumstances for yyou.

**Comment by anaestheticsapp** [comment] 2020-07-14 16:58
Thanks. It's a Safari bug so not much I can do but probably can create a workaround to restart the database when it happens but need more data on when its happening. Hoping all those issues are fixed with iOS 14...

**Comment by leoric23** [comment] 2020-07-17 10:13
i have it happening 2-3 times each day always after an idle period. it doesn't always appear after being idle though. so far i could not establish any pattern.

**Comment by anaestheticsapp** [comment] 2020-07-17 11:03
Can you try updating to iOS 13.5 and see if it resolves? Not been able to reproduce on my test iPhone for the past few days but it's running the newest iOS.

**Comment by leoric23** [comment] 2020-07-17 14:45
probably a really good call. will do. will report back in ~10 days

**Comment by anaestheticsapp** [comment] 2020-07-27 11:22
Not able to reproduce this issue on iOS 13.5.1 so far, but applying the next logbook update will occasionally delete the app database and prevent any read or write operations. As a result, the app will stop working after the update. Fixed after restarting the app with no further issues. Interestingly, no error messages are produced which makes debugging even more difficult.

All problems seem to be fixed with the recent release of iOS 13.6, although not been able to test this for long. Early reports of apps freezing again when multi-tasking. Not been able to reproduce this yet.
https://developer.apple.com/forums/thread/654772

**Comment by anaestheticsapp** [comment] 2020-08-19 21:59
https://bugs.webkit.org/show_bug.cgi?id=197050

**Comment by anaestheticsapp** [comment] 2020-10-27 15:36
Made a few changes to worker code to see if frequency of database errors can be reduced

**Comment by leoric23** [comment] 2020-10-27 16:52
i can tell you that i have never gotten the error again after you added the workaround

**Comment by anaestheticsapp** [comment] 2020-10-28 12:55
Thanks that's good to know! I occasionally still see this error after updating the app - all cases temporarily disappear and cases cannot be added (because the database cannot be accessed) but after 10sec or so the database throws an error and the workaround restarts the app, allowing access to the database again.

**Comment by anaestheticsapp** [comment] 2022-05-23 14:35
IndexedDB is finally fixed in iOS>15. Major problems with iOS 14.6 and as such minimum system requirement for Safari on iOS/MacOS has been changed to iOS 15.3.

**Closed as completed by anaestheticsapp** 2022-05-23 14:35 UTC
Labels: browser bug
